[package]
name="wre-revu-assistant"
version="0.2.0"
description="WRE Revu Assistant"
authors=["WRE"]
edition="2021"
[lib]
name="wre_revu_assistant_lib"
crate-type=["staticlib","cdylib","rlib"]
[build-dependencies]
tauri-build={version="2",features=[]}
[dependencies]
tauri={version="2",features=[]}
serde={version="1",features=["derive"]}
serde_json="1"
lopdf="0.34"
